version: '3'

services:
  distro:
    image: alpine
    container_name: custom_distro
    restart: always
    entrypoint: tail -f /dev/null

  database:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ../dump:/tmp/

  web:
    image: nginx:latest
    container_name: web-server 
    ports:
     - 8081:80
    volumes:
      - ./mysite.template:/etc/nginx/conf.d/mysite.template
    environment:
      - NGINX_HOST=sample.com 
      - NGINX_PORT=80
    links:
      - database:db 
      - distro 

volumes:
  data: 
    external: true