version: "3"
# ----- service 1 -----
services:
  web:
    image: anshuldevops/frindly_hello
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.1"
          memory: 20M
      restart_policy:
        condition: on-failure
    ports:
      - 8085:80
    networks:
      - webnet
# ----- service 2 -----
  visualizer:
    image: dockersamples/visualizer
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
# ----- service 3 -----
  tomcat:
    image: tomcat
    ports:
      - "8088:8080"
    networks:
      - webnet
# ----- service 4 -----
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - "./data:/data"
    deploy:
      placement:
        constraints: [node.role == manager]
    command: redis-server --appendonly yes
    networks:
      - webnet

networks:
  webnet:
